name: Test Halaman IDM

on:
  push:
    paths:
      - "src/pages/Idm.jsx"
      - "cypress/e2e/test-Idm.cy.js"

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run App
        run: npm run dev &
      
      - name: Wait for App
        run: npx wait-on http://localhost:5173

      - name: Run Cypress Test IDM
        run: npx cypress run --spec "cypress/e2e/test-Idm.cy.js"